openapi: 3.0.0
info:
  title: Requirements API
  version: 1.0.0
  description: >
    API for extracting requirements from XML documents.

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:

  /jobs:
    post:
      summary: Submit a new job to extract requirements from a document
      description: Submit an XML file for asynchronous parsing. Returns a job ID.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: XML file to parse
      responses:
        '201':
          description: Job created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                    description: Unique identifier for the job
                  status:
                    type: string
                    description: Current status of the job (e.g., "pending", "processing")
        '400':
          description: Bad request (missing file)

  /jobs/{jobId}/results:
    get:
      summary: Retrieve results for a job
      description: Get the parsing results for a previously submitted job.
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
          description: ID of the job to fetch results for
      responses:
        '200':
          description: Parsing results
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                  status:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
        '404':
          description: Job not found
  
  /parse/sync:
    post:
      summary: Synchronously parse an XML element
      description: Submit an XML element to parse immediately. The entire XML will be parsed; no elementName is needed.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - xml
              properties:
                xml:
                  type: string
                  description: The full XML content to parse
      responses:
        '200':
          description: Parsing results for the XML document
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
        '400':
          description: Bad request (e.g., missing XML)
