service: requirements-api

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
